"""Externally visible runtime constants mirrored from Go."""

TASK_QUEUE = "temporal-agent-harness"

SIGNAL_UPDATE_SESSION_STATUS = "update_session_status"
QUERY_GET_AGENT_WORKFLOW_ID = "get_agent_workflow_id"

QUERY_GET_CONVERSATION_ITEMS = "get_conversation_items"
QUERY_GET_TURN_STATUS = "get_turn_status"
UPDATE_USER_INPUT = "user_input"
UPDATE_INTERRUPT = "interrupt"
UPDATE_SHUTDOWN = "shutdown"
UPDATE_APPROVAL_RESPONSE = "approval_response"
UPDATE_ESCALATION_RESPONSE = "escalation_response"
UPDATE_USER_INPUT_QUESTION_RESPONSE = "user_input_question_response"
UPDATE_COMPACT = "compact"
SIGNAL_AGENT_INPUT = "agent_input"
SIGNAL_AGENT_SHUTDOWN = "agent_shutdown"
UPDATE_PLAN_REQUEST = "plan_request"
UPDATE_MODEL = "update_model"
UPDATE_GET_STATE_UPDATE = "get_state_update"
QUERY_GET_MCP_TOOLS = "get_mcp_tools"
UPDATE_LIST_EXEC_SESSIONS = "list_exec_sessions"
UPDATE_CLEAN_EXEC_SESSIONS = "clean_exec_sessions"
UPDATE_APPROVAL_MODE = "update_approval_mode"
UPDATE_PERSONALITY = "update_personality"
QUERY_LIST_SKILLS = "list_skills"
UPDATE_TOGGLE_SKILL = "toggle_skill"
UPDATE_SESSION_NAME = "set_session_name"
UPDATE_REASONING_EFFORT = "update_reasoning_effort"

QUERY_GET_SESSIONS = "get_sessions"
UPDATE_START_SESSION = "start_session"

PHASE_WAITING_FOR_INPUT = "waiting_for_input"
PHASE_LLM_CALLING = "llm_calling"
PHASE_TOOL_EXECUTING = "tool_executing"
PHASE_APPROVAL_PENDING = "approval_pending"
PHASE_ESCALATION_PENDING = "escalation_pending"
PHASE_USER_INPUT_PENDING = "user_input_pending"
PHASE_COMPACTING = "compacting"
PHASE_WAITING_FOR_AGENTS = "waiting_for_agents"

AGENT_STATUS_PENDING_INIT = "pending_init"
AGENT_STATUS_RUNNING = "running"
AGENT_STATUS_COMPLETED = "completed"
AGENT_STATUS_ERRORED = "errored"
AGENT_STATUS_SHUTDOWN = "shutdown"
AGENT_STATUS_NOT_FOUND = "not_found"

ITEM_TYPE_USER_MESSAGE = "user_message"
ITEM_TYPE_ASSISTANT_MESSAGE = "assistant_message"
ITEM_TYPE_FUNCTION_CALL = "function_call"
ITEM_TYPE_FUNCTION_CALL_OUTPUT = "function_call_output"
ITEM_TYPE_WEB_SEARCH_CALL = "web_search_call"
ITEM_TYPE_COMPACTION = "compaction"
ITEM_TYPE_MODEL_SWITCH = "model_switch"
ITEM_TYPE_TURN_STARTED = "turn_started"
ITEM_TYPE_TURN_COMPLETE = "turn_complete"
